config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  has_many:recipes
  before_save{self.email=email.downcase}
  validates :chefname,presence: true,length:{maximum:40}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence:true, uniqueness:{case_sensitive:false},format: {with: VALID_EMAIL_REGEX },length:{maximum:255}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef
  validates :name,presence: true,length:{minimum:5,maximum:30}
  validates :description,presence: true,length:{minimum: 5,maximum: 50}
  validates :chef_id,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_param,only:[:show,:edit,:update]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.first
    if @recipe.save
      flash[:success] = "Recipe was created succesfully"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success]="Your recipe was edited succesfully"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
     Recipe.find(params[:id]).destroy
     flash[:success] = "Recipe deleted succesfully"
     redirect_to recipes_path
  end


private
  def recipe_params
      params.require(:recipe).permit(:name,:description)
  end

  def set_param
    @recipe = Recipe.find(params[:id])
  end



end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(chef, options={size:80})
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:chef.chefname, class:"img-circle")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
       <p>Yoset Grajeda &copy; 2018 DymCorp</p>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name,msg| %>
    <div class="alert alert-<%=name%>">
      <a href="#" class="close" data-dismiss="alert"> &#215; </a>
      <%= msg%>
    </div>
    <%end%>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Recipes", root_path,class:"navbar-brand",id:"logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/messages'%>

    <div class="container">
      <%= yield %>
      </div>
      <%= render 'layouts/footer'%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1 align>Welcome my recipes app</h1>
  <h2>The best recipes sharing app</h2>
  <p><%=link_to "Sign up or Log in","#",class:"btn btn-danger btn-lg"%></p>
</div>
<div class="row">
       <div class="col-lg-4">
         <h2>Safari bug warning!</h2>
         <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
         <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
         <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
       </div>
       <div class="col-lg-4">
         <h2>Heading</h2>
         <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
         <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
      </div>
       <div class="col-lg-4">
         <h2>Heading</h2>
         <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
         <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
       </div>
     </div>

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(@recipe.errors.count, "error")%>
          prohibited this <%= @recipe.class %> from being saved:
        </h2>

        <div class="panel-body">
            <ul>
              <% @recipe.errors.full_messages.each do |msg|%>
                <li><%= msg%></li>
              <%end%>
            </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<%end%>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe,:html => {class:"form-horizontal",role:"form"}) do |f|%>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
          <div class="col-md-8">
            <%= f.text_field :name, class:"form-control",placeholder:"Name of recipe",autofocus:true%>
          </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows:10,class:"form-control",placeholder:"Description of the recipe",autofocus:true%>
          </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class:"btn btn-primary btn-lg btn-xlarge"%>
        </div>
      </div>
      <div class="col-md-4 col-md-offset-4 colormatch">
        [ <%= link_to "Cancel request and return to recipes listing",recipes_path%> ]
      </div>
      </div>
    <%end%>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title',title:"Edit recipe"%>
<%= render 'recipes/form'%>

app/views/recipes/index.html.erb
<%= render 'shared/page_title',title:"showing all recipes"%>



<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%=link_to gravatar_for(recipe.chef,size:120),recipes_path%>
        <p class="center"><%=recipe.chef.chefname%></p>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4> <%=link_to recipe.name, recipe_path(recipe)%> </h4>
      <p> <%= truncate(recipe.description,length:150)%> </p>
      <p>
        <span class="quiet"> <small> Created <%= time_ago_in_words(recipe.created_at)%> ago</small></span>
        </p>
    </div>
  </div>


<%end%>

app/views/recipes/new.html.erb
<%= render 'shared/page_title',title:"create a new recipe"%>
<%= render 'recipes/form'%>

app/views/recipes/show.html.erb
<%= render 'shared/page_title',title:@recipe.name%>
<div class="well col-md-8 col-md-offset-2">
  <h4 class="description center"> <strong>Steps:</strong> </h4>
  <hr>
  <%=simple_format(@recipe.description)%>
  <hr>
  <div class="pull-right">
    <p class="center">
    <em>Created by:</em>
    </p>
    <p class="center"><%=link_to gravatar_for(@recipe.chef),recipes_path%></p>
    <p class="center">
      <small> <%= @recipe.chef.chefname.capitalize %> </small>
    </p>
    <div class="pull-right">
        Created : <%= time_ago_in_words(@recipe.created_at)%>
    </div>
  </div>
  <div class="recipe-actions">
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class:"btn btn-xs btn-warning"%>
    <%= link_to "Delete this recipe", recipe_path(@recipe), method: :delete,
                                      data:{ confirm: "Are you sure you want to delete this recipe?" },
                                      class: "btn btn-xs btn-danger"%>
  </div>
</div>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr>